services:
  - type: web
    name: v3k-backend-api
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
