services:
  - type: web
    name: v3k-backend-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python-3.10.13
    region: oregon
